sonar.projectKey=forward-support-web
sonar.projectName=Plataforma de Soporte - Web

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx,**/coverage/**

sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.sourceEncoding=UTF-8
