sonar.projectKey=forward-support-web
sonar.projectName=Plataforma de Soporte - Web

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx,**/coverage/**,src/testing/**,src/shared/api/testing.ts

sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.sourceEncoding=UTF-8

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
